### ISSUE TITLE
Update apartment route

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#105]
route:
**PATCH /apartments/:id**
##
**Recieve**

|            Property          |   Sub-Properties            |     requirement           |             comment                |
|------------------------|---------------------------|------------------------|------------------------------|
| address | state, city, street, number| OPTIONAL||
|            price               || OPTIONAL||
|            enteranceDate ||OPTIONAL||
|            images ||OPTIONAL||
|            description||OPTIONAL||
|            tags||OPTIONAL||
|            requiredNumberOfRoommates||OPTIONAL||
|            currentlyNumberOfRoomates||OPTIONAL||
|            numberOfRooms||OPTIONAL||
|            floor||OPTIONAL||
|            totalFloors||OPTIONAL||
|            area||OPTIONAL||

Also a user must be connected in order to perform request (this condition is checked on server side) and can only updated his/her published apartments.

**Returns:**
updated apartment JSON

**Comment by OrAbramovich** [comment]
Done.
