### ISSUE TITLE
Front-end: Check integration of web template with Vue

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#112]

**Comment by alonttal** [comment]
I upload the template here, to clean the repository
[frontend_template_based.zip](https://github.com/TechnionYearlyProject/Roommates/files/1584181/frontend_template_based.zip)

**Comment by OrAbramovich** [comment]
The design is going to be similar to the one in the template but it won't be a copy-paste. We have to generate a similar one with Vue.
