### ISSUE TITLE
Sprint One - presentation

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#113]
The back end is ready, please work on the front end part.
v. 1
[sprint1.pptx](https://github.com/TechnionYearlyProject/Roommates/files/1584180/sprint1.pptx)
v. 2
[sprint1.pptx](https://github.com/TechnionYearlyProject/Roommates/files/1584437/sprint1.pptx)
v. 3
[sprint1.pptx](https://github.com/TechnionYearlyProject/Roommates/files/1584888/sprint1.pptx)
v. 4
[sprint1.pptx](https://github.com/TechnionYearlyProject/Roommates/files/1584959/sprint1.pptx)
v.5
[sprint1.pptx](https://github.com/TechnionYearlyProject/Roommates/files/1585698/sprint1.pptx)

**Comment by alonttal** [comment]
v. 3
sprint1.pptx

**Comment by alonttal** [comment]
v. 4 
added "questions?" slide

**Comment by idanyadgar** [comment]
v.5 uploaded.
Added front end slides.

**Comment by OrAbramovich** [comment]
Done. Link was added to the Wiki.
