### ISSUE TITLE
Add comment route

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#116]
route:
PUT /apartments/:id/comment

Property | requirement | comment
-- | -- | --
text | OPTIONAL  | 10-1000 chars |  

Also a user must be connected in order to perform request (this condition is checked on server side).

Returns:
updated apartment comments JSON

**Comment by OrAbramovich** [comment]
Done.

**Comment by alonttal** [comment]
Hi,
I think it should be POST, not PUT
