### ISSUE TITLE
Back-end: Complete all back-end routes (+tests)

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#125]
Route| Route Implementation Status| Route Testing Status | Priority
-- | -- | --  | --
POST /apartments | Done | Done | High
PUT /apartments/id/comment | Done | Done | High
PUT /apartments/id/interested | Done   | Done  | High
DELETE /apartments/id | Done | Done | High  
GET /apartments | Done | Done | High
POST /users | Done | Done | High
GET /users/id | Done | Done | High
GET /users/id | Done | Done | High
PATCH /users/id | Done | Done  | High
GET /users/tags | Done | Done | High
GET /apartments/tags | Done | Done | High
PATCH /apartments/id | - | - | Low

**Comment by alonttal** [comment]
Good Summary.
Thanks!

**Comment by OrAbramovich** [comment]
GET /apartments/tags - done.

**Comment by OrAbramovich** [comment]
GET /apartments/tags tests - done.

**Comment by OrAbramovich** [comment]
GET /users/tags tests - done.

**Comment by alonttal** [comment]
please add these 2 routes:
GET users/:id/published
GET users/:id/interested

**Comment by OrAbramovich** [comment]
All relevant routes are done.
