### ISSUE TITLE
All Apartment Tags and User Tags

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#131]
List here all the apartment tags and user tags you are using in the front end,
so we can keep it synchronized with the back end.

tags within '[]' are not supported in backend yet (not added yet).
If you add a tag to back end make sure to remove the [] from it!

### Apartment Tags: 
|id|name|
|--|------|
|1|ac|
|2|pets|
|3|elevator|
|4|terrace|
|5|parking|
|6|storage|
|7|Kosher Kitchen|
|8|Furnished|

### User Tags: 
|id|name|
|--|------|
|1|vegan|
|2|non-smoking|
|3|quite|
|4|outgoing |
|5|night person|
|6|daily person|
|7|relegious|
|8|interested in sport|
|9|interested in culinary|
|10|interested in politics|
|11|interested in music|
|12|interested in history|
|13|interested in arts|
|14|Kosher Keeper|

**Comment by idanyadgar** [comment]
I believe we should add "Kosher Kitchen" and "Furnished" tags to apartment, and "Kosher Keeper" to user tags.

**Comment by alonttal** [comment]
@idanyadgar 
Added to list.

**Comment by alonttal** [comment]
"Kosher Kitchen" and "Furnished" tags to apartment, and "Kosher Keeper" to user tags were **added**.

**Comment by OrAbramovich** [comment]
Done.
