### ISSUE TITLE
Create Final Presentation

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#161]

**Comment by alonttal** [comment]
first 3 pages,
please write here if you continue working on it.
[endSemester.pptx](https://github.com/TechnionYearlyProject/Roommates/files/1648771/endSemester.pptx)

**Comment by OrAbramovich** [comment]
V2.0 - added some slides (design is needed)
[endSemester.pptx](https://github.com/TechnionYearlyProject/Roommates/files/1649278/endSemester.pptx)

**Comment by alonttal** [comment]
done. @OrAbramovich  will upload final version soon.

**Comment by OrAbramovich** [comment]
V4.0
[Project.pptx](https://github.com/TechnionYearlyProject/Roommates/files/1650825/Project.pptx)

**Comment by OrAbramovich** [comment]
[V5.0](https://github.com/TechnionYearlyProject/Roommates/files/1651203/Project.pptx)

Done.

**Comment by OrAbramovich** [comment]
[V6.0](https://github.com/TechnionYearlyProject/Roommates/files/1653298/Project.pptx)

Last one.
