### ISSUE TITLE
turn apartment page dynamic

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#163]
finish the apartmentPage display by using real data and not static

adjust display to use the correct field of apartment and auther of apartment

**Comment by alonttal** [comment]
What's the status?

**Comment by chananbental** [comment]
currently:
user can show interest
the apartment and ad auther are dynamic

only thing left is adding comment

**Comment by chananbental** [comment]
layout is similar to the mock now

still the PUT apartment/:id/comment is not working

**Comment by alonttal** [comment]
i did it. done.
