### ISSUE TITLE
Add some documentation to back-end

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#179]

**Comment by alonttal** [comment]
added to:
- arrayFunctions.js
- removeFalsyProps.js
- matcher.js

**Comment by alonttal** [comment]
added to:
- authenticate.js
- cors.js
- vuejs.js
- apartment.js

**Comment by alonttal** [comment]
added to:
- hobbie.js
- tag.js
- ticket.js
- user.js

**Comment by OrAbramovich** [comment]
Added to server.js

**Comment by alonttal** [comment]
done.
