### ISSUE TITLE
Document: Design location reviews feature

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#194]
find ways for reviewing loctaion of apartments.
research the suggested solutions and their aplicativty.
suggest final solution.
[location review feature](https://github.com/TechnionYearlyProject/Roommates/wiki/location-review-feature)

**Comment by OrAbramovich** [comment]
Hi Chana, does the Google API provide neighborhood and places reviews? I think that it provides reviews for specific locations (e.g. restaurants etc.) 


https://developers.google.com/places/web-service/details

**Comment by chananbental** [comment]
by the looks of it' it seems it does not.
that is a downside to theis solution.
we can assume that nearby facilaties will show up on the map in the apartment page which can go around that problem.
i will look around to see if maybe we can get a list of the newarby facilaties for the API using the coordinates that we save for the apartment

**Comment by chananbental** [comment]
the google API does indeed let as get a list of nearby facilaties
i will add this info to the document

**Comment by chananbental** [comment]
unfortantly due to limted languge features in GitHub i will need to translate the document to Englisg, unless someone know how to get GitHub t recognize Hebrew

**Comment by alonttal** [comment]
Hi Chanan,
you haven't provided any substantial solution to the problem, beside the one @OrAbramovich proposed.
please update the file and describe alternative we can actually use.
Also please transfer the document into English.

**Comment by chananbental** [comment]
i finished the transketion.
i will continue to look for a solution

**Comment by OrAbramovich** [comment]
See Yad-2 example: http://homeprices.yad2.co.il/reviews/%D7%97%D7%99%D7%A4%D7%94/%D7%94%D7%A6%D7%A4%D7%99%D7%A8%D7%94

**Comment by chananbental** [comment]
as discused we will have a rated part (as before) and a review by people like in Yad-2 for every <road,city>
we are waiting for the "go ahead" from the client.
i have also contacted Madlan to see if we can get premission to use there info.

**Comment by omrihuller** [comment]
week 3: should also start implementing

**Comment by chananbental** [comment]
final solution acording to yesterday group meeting add to document
