### ISSUE TITLE
Document: Write an article (final report) about Roommates

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#197]

**Comment by OrAbramovich** [comment]
Time estimation: 9 hours per person

**Comment by alonttal** [comment]
Eventually it took much more, about 2.5 days each..

**Comment by OrAbramovich** [comment]
[Roommates.v.1.5.pdf](https://github.com/TechnionYearlyProject/Roommates/files/1886685/Roommates.v.1.5.pdf)

**Comment by OrAbramovich** [comment]
Done. 
[Roommates Report.pdf](https://github.com/TechnionYearlyProject/Roommates/files/1887882/Roommates.Report.pdf)
