### ISSUE TITLE
Back-end: Add support for multiple owners of apartment

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#200]
[ To be filled by the assignee ]

**Comment by alonttal** [comment]
How about a simple list with all the owners in the Apartment model?
approved?

**Comment by omrihuller** [comment]
Sounds good, 
When adding an owner do you ask all other owners for permission? Or just the first?

**Comment by alonttal** [comment]
Good question...
I think it's redundant (it least for now).
What do you think?

**Comment by omrihuller** [comment]
I think asking the first owner (only) makes sense.
I agree that implementing it isn't a priority at the moment,
We can start by letting anyone claim ownership at first.

**Comment by alonttal** [comment]
how about:
The publisher adds additional owners (other users are not permitted)
?

**Comment by omrihuller** [comment]
Good idea

**Comment by alonttal** [comment]
Any more opinions? Anyone else?

**Comment by OrAbramovich** [comment]
Time estimation: 1.5 hours.

**Comment by alonttal** [comment]
Added Nice-To-Have tag

**Comment by OrAbramovich** [comment]
@alonttal , Agreed that not in scope right?

**Comment by idanyadgar** [comment]
Agreed.

**Comment by OrAbramovich** [comment]
Not in scope.
