### ISSUE TITLE
Design: Notification system design - review & approve

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#218]
I have wrote a document about the notification system feature with some general ideas and options for your review. Once approved - will open specific issues & will be prioritized.
You can find it @ our Wiki: [Notification System Feature](https://github.com/TechnionYearlyProject/Roommates/wiki/Notifications-System)

Assigned to all team members. Feel free to comment.

**Comment by alonttal** [comment]
Hi @OrAbramovich ,
The decision between creating a new "Notification" Schema and embending it inside the existing "User" Schema depends on what we are planning to do with the notifications.
If we decide that we want to have a way of searching for notification or creating other tasks that require fast fetching, then Schema is a better choice for sure - each Notification instance will be related to exactly one user (by ID), and we'll be able to use mongoose's smart queries to filter the data.
On the other hand, if we are not planning to do more than that - then a simple "notifications" list inside the User's class will do the job (and will be less complicated).

**Comment by OrAbramovich** [comment]
Decided. The design document was updated with the chosen way.
