### ISSUE TITLE
Testing: Back-end: Fix geolocation failing test

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#245]
Fix CI failing test "should return correct geo-location for the given address"

**Comment by OrAbramovich** [comment]
Allowed 150 meters difference (instead of 100m) as a temp commit so the builds can pass.

**Comment by OrAbramovich** [comment]
Time estimation: 1.5 hour

**Comment by alonttal** [comment]
@OrAbramovich 
is it closed?
