### ISSUE TITLE
Design: Location review, writen part sources

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#247]
find viable sources for wirten part of a location review

**Comment by OrAbramovich** [comment]
See Yad-2 example: http://homeprices.yad2.co.il/reviews/%D7%97%D7%99%D7%A4%D7%94/%D7%94%D7%A6%D7%A4%D7%99%D7%A8%D7%94

**Comment by chananbental** [comment]
will be a mockup for the begining plus written reviews by users
