### ISSUE TITLE
Design: UI design

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#25]
UI tasks for the 06.11.2017 - 12.11.2017 (based on the weekly meeting protocol):

* decide on interface, taking into consideration: components, functionality & looks.
* research and make a guide on Bootstrap.
* decide, research & make a guide on tools that will ease implementation. options: JQuery. vue.js - easy to learn. Not compatible to making mobile app. Angular (Ionic) - harder to learn. Compatible to making mobile app.

**Comment by alonttal** [comment]
implementation already started.
