### ISSUE TITLE
Back-end: support new hobbies formation

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#251]
follow up to #240

**Comment by Danielohayon** [comment]
Changed the UserSchema in the backend module to include a new array of hobbies that are blockers called blockers. Meaning that every hobby in the array hobbies is considered as a yes, every hobby in the blockers array is considered as a firm no, meaning a blocker. And finally every hoody that is not in the hobbies array and not in the blockers array is considered as a "Don't Care".

So the heuristic for calculating a match between two users will be as follows: 

Person A/Person B | I am | Don't care | No way
-- | -- | -- | --
**I am** | +1 to the matching sum | +0 to the matching sum | Matching result  is set to 0
**Don't care** | +0 to the matching sum | +0 to the matching sum | +0 to the matching sum
**No way** | Matching result  is set to 0 | +0 to the matching sum | +1 to the matching sum
