### ISSUE TITLE
Back-end: Notification system implementation

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#253]
beginning the implementation suggested in #218

**Comment by OrAbramovich** [comment]
Time estimations:
- Make sure design fits the new needs - 1 hour
- Change DB schemas - 1 hour
- Add relevant functionalities to current models - 2 hours.
- Create notifications module - 4 hours.
- Create notifications module unit tests - 3 hours.
- Update current routes - 2.5 hours.
- Create/modify integration tests for the updated routes - 3 hours.
- Support live notifications (learning socket.io + implementation) - 5 hours.

Total: 21.5 hours.

**Comment by OrAbramovich** [comment]
Done.

Notifications feature is done on server side. It includes the following:
1. Notification DB schema & module providing relevant functionalities.
2. Notifications Aggregation Policy logic.
3. Updated apartment & user DB schemas and functionalities.
4. Notifier service which sends notifications to DB and real time.
5. Sockets server providing real-time notifications sent to the front-end.
6. Updated existing routes to push notifications.
7. New relevant routes.
8. Tests.
9. Documentation available @ our Wiki.
