### ISSUE TITLE
Design: Location review: struct design

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#265]

**Comment by chananbental** [comment]
{
id: obectID,
street name: string,
city: string,
rated characteristics: 
    {
         parking: real,
         publicTransport: real,
         noise: real,
         commercialServices: real,
         upkeep: real,
         general rating: real
     },
voters: [objectID, objectID],
usersRevies: [
          {
                    _createdBy: ObjectID,
                    review: string
          }
        ]
}

**Comment by OrAbramovich** [comment]
Hi @chananbental ,
I think you should consider to add geo-location data (longtitude and latitude) since:
1. We will be able to give a review for the area (e.g. of 500 meters).
2. It's a normal form: user might type "מלל" and the other one "מל"ל" etc.

**Comment by chananbental** [comment]
good point @OrAbramovich , thanks
ill update in the document i am writing, ill add a link when i finish

**Comment by chananbental** [comment]
[locatin review API](https://github.com/TechnionYearlyProject/Roommates/wiki/API-for-location-review)
