### ISSUE TITLE
decide on interface

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#27]
decide on interface, taking into consideration: components, functionality & looks. #25 

[Interface Draft.pdf](https://github.com/TechnionYearlyProject/Roommates/files/1463818/Interface.Draft.pdf)
  
 current pages: 
- home page: search fields. login & register or user profile.
- register page: user fields
- search results page: preview of search results in pages.
- apartment page: apartment details, photos, comments, interested users and owner profile link
- my profile: describes the logged in user profile and allows editing 
- user profile: describes another user, search together option
- about/contact us: short paragraph about us and contact info
EDIT: as a result of our weekly meeting we will add a search option for roommates in addition to the apartment search

additional features:
- login pop-up
- add comment pop-up
- show address on map pop-up
- terms of service pop-up
- navigation menu: currently on the left, can be on the top instead. need to decide about collapsible.

**Comment by alonttal** [comment]
implementation started
