### ISSUE TITLE
Back-end: Add route: PUT /apartments/:id/subscription

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#270]
The above route is going to be used by a registered user to toggle a subscription to an apartment ad. A subscribed user will get notifications about: comments, likes and modifications of the ad.

**Comment by OrAbramovich** [comment]
Estimated time: 0.5 hour.

**Comment by alonttal** [comment]
Hi @OrAbramovich
I think it should be like this:
Recieve notification should be toggled to "true" by default. When a "recieve notifications on.." object is added to the list the user will recieve notifications. This object will have an on/off flag. If a user decides to disable receiving a specific notification this object So each notification object will have field the flag is set to "off". In particular, the object should not be removed from the list.

**Comment by OrAbramovich** [comment]
Actual time: 0.5 hour.

**Comment by OrAbramovich** [comment]
Done.
