### ISSUE TITLE
BackEnd: add route: POST /reviews

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#274]

**Comment by alonttal** [comment]
lets keep it in the convention:
POST /review**s**

**Comment by chananbental** [comment]
fixed

**Comment by chananbental** [comment]
estimated: 1 hour
actual time 3 hours
(including tests)
done and closed

**Comment by chananbental** [comment]
need to check that no review by the same user has been geiven in the area allready

**Comment by chananbental** [comment]
done
