### ISSUE TITLE
BackEnd: add route: PUT /reviews/:id

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#275]

**Comment by alonttal** [comment]
hi Chanan:
"PUT /review" is enough
the request body will contain all the data

**Comment by chananbental** [comment]
ok

**Comment by chananbental** [comment]
are you sure?
who's id is in the route?
the way it works is that each street has an entry in the database with its reviews.
therefore when i want to add a new review i look for the street using the city and street
so why would it not be reviews/:city/:street?

**Comment by OrAbramovich** [comment]
@chananbental , before you start with the routes please create tests for the reviews model and make sure they pass. It seems that there are bugs there.

**Comment by chananbental** [comment]
this issue is irelevent because of the design change
now that we save each review by its self and not for each road this route means nothing
