### ISSUE TITLE
BackEnd: add route: GET /reviews?=[city=],[street=]...[]

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#276]

**Comment by alonttal** [comment]
hi Chanan,
it will be better change the parameters to query parameters,
so then we'll be able to fetch reviews by any parameter we want (or add additional parameters in the future, for example find by geolocation, radius, etc..)
so:
GET /reviews?=[city=<city>],[street=street],

**Comment by chananbental** [comment]
good idea

**Comment by chananbental** [comment]
for now the route is only for coordinate
