### ISSUE TITLE
Back-end: Create route for fetching users list by ids

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#317]

**Comment by OrAbramovich** [comment]
Actual time: 0.5 hour.

**Comment by OrAbramovich** [comment]
@alonttal,
As agreed - modified the GET /users/:id route to support single value or array as id parameter. The returned value is a JSON map that its properties are the ids and the value for each one is the relevant user document.

Please make the relevant changes in front-end. 

BTW - it seems that the received value for array is a string separated by ',' and not an array object.

**Comment by OrAbramovich** [comment]
Done.

**Comment by alonttal** [comment]
reopened.
@OrAbramovich 
I've looked at the code. The reason you get the ids as a long string is due to the use of "params". In such cases, query is more appropriate. I'll change that and modify the test accordingly.
Estimated time: 1 hour.

**Comment by alonttal** [comment]
I've pushed the change.
closed
