### ISSUE TITLE
Back-end: Add private messaging functionality to the sockets server

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#319]
The socket server has to provide private messaging functionalities.

**Comment by OrAbramovich** [comment]
Estimated time: 3 hours.

**Comment by alonttal** [comment]
Hi @OrAbramovich 
is it possible to move the sending of the jwt token from the connect phase to the join phase?
I think it's more reasonable and also ease the work on the front-end side.

**Comment by alonttal** [comment]
hi @OrAbramovich ,
isn't this already closed?

**Comment by alonttal** [comment]
@OrAbramovich 
closed?

**Comment by OrAbramovich** [comment]
Yes.

**Comment by OrAbramovich** [comment]
Actual time: 4 hours.

**Comment by OrAbramovich** [comment]
Done.
