### ISSUE TITLE
reviews: decide on review cleenup protocol

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#325]

**Comment by alonttal** [comment]
What is that?

**Comment by chananbental** [comment]
[Review cleen up design](https://github.com/TechnionYearlyProject/Roommates/wiki/design-review-cleenup-algorithem)
done
will start implementing stright away, sorry for the delay i was not filling well the past few days
time this took 4 hours (checking other websites, finding out that my original idea might be NP-hard).
