### ISSUE TITLE
Design: Notify user about new apartments he might be interested in

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#335]
New feature: the platform should be able to notify (notification + email) a registered user about new apartments he might be interested in according to his last searches. The task is writing a design document for the feature.

**Comment by OrAbramovich** [comment]
Time estimation: 1.5 hours

**Comment by OrAbramovich** [comment]
The suggestion should be based on past history search.

**Comment by OrAbramovich** [comment]
Estimated time: 2 hours.

**Comment by chananbental** [comment]
a sektch for the design:
save in a tree formation all the users acoording to search:
have 1 main json that saves an array of data for every country, every countrywill save an array of cities, and so on for each search parameter.
* search history{
    * country array [
        * city array [
            * price_range array [
                * users array [
                        * user1,
                        * user2,
                        * user3

                ]

            ]

        ]

    ]

}
when ever a new apartment is added we will check the coorsopnding search in the search tree to find the list of users that searched for this kind of apartment.

what do you think of this as a base?

**Comment by chananbental** [comment]
i think i am finished, waiting for OK from @OrAbramovich 
should i add the back end API?
link to doc is in previous comment

**Comment by chananbental** [comment]
Sounds like a good idea.
Ill get on it once i ginish the nust, should be very soon

**Comment by chananbental** [comment]
![image](https://user-images.githubusercontent.com/33029981/40585795-25fbdf42-61c1-11e8-8019-7985a6e93bb8.png)

**Comment by chananbental** [comment]
actual time 7 hours
waiting for final OK

**Comment by chananbental** [comment]
done
working on implementaion #534
