### ISSUE TITLE
Add apartment contacts card

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#366]
which will display all the publishers info.

**Comment by OrAbramovich** [comment]
Time estimation:3 hours.

**Comment by chananbental** [comment]
just to be sure, you want me to add in the apartment page the contact info of the publisher?

**Comment by chananbental** [comment]
i dont think i understand this issue, it seems this allready exits
![image](https://user-images.githubusercontent.com/33029981/40510284-df096abe-5fa4-11e8-8540-6361763f1095.png)
is this not it?
@alonttal @OrAbramovich

**Comment by alonttal** [comment]
indeed. this was done a while ago by I. forgot to close this issue...

**Comment by alonttal** [comment]
The card will need to be updated when list of contacts will be added to the apartment model.
