### ISSUE TITLE
Classes Definition

### ISSUE THREAD

**Issue by Danielohayon** [TechnionYearlyProject/Roommates#37]
In this issue we will decide the final structure of our classes. 

## Apartment
This class will represent an apartment.

1. String: ID
2. String: City 
3. String: Street 
4. String: Building Number
5. String: Apartment Number 
6. String: Floor 
7. String: Rent Price 
8. String: Number of Rooms
9. String: Number of Showers 
10. String: Number of Bathrooms 
11. List<ApartmentTag> tags //
12. List<Image> Apartment Pictures 
13. List<String> Residents // A list of all the residents IDs
14. List<String> Interested // A list of all the interested users IDs
15. List<Comment> comments //comments on this apartment by renting users
16. String FreeTextDescription 
17. String: Owner's ID In Our Database 

## User
This class will be an abstract class the User-Owner and User-Renter will inherit from.

1. String: ID
2. String: Name
3. String: Email 
4. String: Password
5. String: Phone Number

## User-Owner - Inherits form User
This class will represent a user that posts apartments for rent.

1. List<String> apartments ID's he has posted for rent
2. List<Comment> reviews // reviews of this renter

## User-Renter - Inherits form User
This class will represent a user that is looking for a place to rent and can review apartments and renters.

1. String DateOfBirth
2. String gender
3. Boolean dogOwner // Owns and wants to bring a dog 
4. Boolean catOwner // Owns and wants to bring a cat  
5. Boolean dogAllergy // Allergic to dogs
6. Boolean catAllergy // Allergic to cats
7. List<InterestTag> interests
8. Sting Occupation // this will be from a set multi-choice of student/ employee 
9. String studying // if he is a student this will be relevant and is chosen from a multi-choice of all the possible degrees
10. String freeTextDescription
11. List<image> images // images the user would like to upload of himself 
12. _NEEDS DEBATING: List<Comment> comments about this user_ // comments left on this resident by other residents who have lived with him 

## Comment
This class will represent a comment that will be stored in a list in either Apartment, User-Owner or User-Renter.

1. String ID //comment's id 
2. Sting PosterID // poster's id
3. String content
4. String Date // date of posting

## ApartmentTag
This will be an Enum with the following set values.

1. No Elevator 
2. Pet Free 
3. Comes Furnished 
4. Has Oven 
5. Has Stove

## InterestTag
This will be an Enum with the following set values.

1. Likes Basketball 
2. Likes Football 
3. Plays an instrument
4. Likes to cook 
5. Likes to workout 
6. Likes to watch realityTV
7. Like to watch tv shows 
8. Likes to watch movies 

## Image
This class will represent an image.

1. String ID
2. String Image
3. int pixelHeight
4. int pixelWidth

**Comment by alonttal** [comment]
used apartment, user, apartmenttag, interesttag.
