### ISSUE TITLE
Testing: Back-end: Fix failing tests

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#376]
There are 2 tests (of GET /users) that constantly fail so they should be fixed so the CI build can pass.
The task is to find the bug (in tests or in the code) and fix it.

**Comment by OrAbramovich** [comment]
Estimated time: 0.5 hour.

**Comment by OrAbramovich** [comment]
The route of GET /users/ was modified (with a new logic) but its tests still expected the old values - fixed the 2 tests (for not existing users it returns an empty result instead of an error of BAD REQUEST).

**Comment by OrAbramovich** [comment]
Actual time: 0.5 hour.

**Comment by OrAbramovich** [comment]
CI build is back to the green zone.

Done.

**Comment by alonttal** [comment]
@OrAbramovich
Nice
