### ISSUE TITLE
Create Route for fetching Users ordered by BestMatching

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#377]
It should recieve a list of user ids and return an ordered-map of the users sorted by best-matching.
the key should be the user's id and the value is the user object.
It should require authentication.

**Comment by OrAbramovich** [comment]
@alonttal ,

Still relevant?

**Comment by OrAbramovich** [comment]
Not relevant any more.

**Comment by OrAbramovich** [comment]
Estimated time: 0.5 hour incl updating tests

**Comment by OrAbramovich** [comment]
Actual time: 0.5 hour incl updating tests

**Comment by OrAbramovich** [comment]
Done.
