### ISSUE TITLE
Working with Azure

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#380]
Investigate how to work with Azure and share the information with the team

**Comment by alonttal** [comment]
follow ups:
#420

**Comment by OrAbramovich** [comment]
Move to on-hold. Waiting for architecture design #421

**Comment by chananbental** [comment]
@OrAbramovich @alonttal this is it right to assume this is done?

**Comment by alonttal** [comment]
indeed, thanks.
