### ISSUE TITLE
Back-end: Sockets-server: Support authentication with second roundtrip

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#386]

**Comment by OrAbramovich** [comment]
Time estimation: 0.5 hour

**Comment by OrAbramovich** [comment]
After a lot of investigations -
The front-end & back-end authentication problem was caused by the fact that the front-end performed the a 2 roundtrip authentication and the sockets server didn't allow it (only 1 way was approved i.e. during the initialization).

**Comment by OrAbramovich** [comment]
Code was written on Alon's laptop - will be pushed by him.

**Comment by alonttal** [comment]
done.
Actual time: 2.5 hours
