### ISSUE TITLE
Back-end: Integrate private messaging feature with the sockets server

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#403]
Consists of 2 sub-tasks:

1. Add support of new message - "private message" which is a new private message sent from user A to B + testing - #404 , #405 

2. Add support of new message - "read message" which is an ack that a user read a private message + testing - #409 , #410

**Comment by OrAbramovich** [comment]
Time estimations can be found in each sub-tasks.

**Comment by alonttal** [comment]
Hi @OrAbramovich ,
isn't it already closed?

**Comment by alonttal** [comment]
@OrAbramovich 
closed?

**Comment by OrAbramovich** [comment]
Yes.
