### ISSUE TITLE
Front-end: locations review feature implementation - first phase

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#412]
Create static reviews page which includes reviews + search + add a review.

**Comment by alonttal** [comment]
hey Chanan,
sup?
have you started working on it?

**Comment by chananbental** [comment]
I'm good, how about you?
not yet i was hoping to to talk to you about this, seeing that you might have the best idea where to place this int he front end after your rework.

**Comment by alonttal** [comment]
cool,
anyway, please remove the estimated time, it needs to be assigned and estimated when we actually start working on it.

**Comment by OrAbramovich** [comment]
Estimated time: 2 hours.

**Comment by idanyadgar** [comment]
Done.
Took 5 hours.
