### ISSUE TITLE
Back-end: Support multiple ids on PATCH /users/notifications/:id

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#418]

**Comment by OrAbramovich** [comment]
Time estimation: 0.5 hour

**Comment by OrAbramovich** [comment]
To be updated in front-end (once done).

**Comment by alonttal** [comment]
#427 related

**Comment by OrAbramovich** [comment]
@alonttal , 
Changed the id list passed to route PATCH /users/notifications/:id to be query instead of a single param (so the new route is PATCH /users/notifications). Added tests so you can take usage examples.

**Comment by OrAbramovich** [comment]
Actual time: 0.5 hour incl changing functions in user model (and places that called those functions).

**Comment by OrAbramovich** [comment]
Done
