### ISSUE TITLE
Fix the notifications in front-end after PATCH /user/notification route change

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#427]

**Comment by OrAbramovich** [comment]
@alonttal ,
Changed the id list passed to route PATCH /users/notifications/:id to be query instead of a single param (so the new route is PATCH /users/notifications). Added tests so you can take usage examples.

**Comment by alonttal** [comment]
Thanks @OrAbramovich 
estimated time: 1 hour.

**Comment by alonttal** [comment]
done.
