### ISSUE TITLE
Integrate with Azure image storage

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#428]

**Comment by idanyadgar** [comment]
Time estimation: 5h.

**Comment by idanyadgar** [comment]
Done.

**Comment by idanyadgar** [comment]
Hey.
Yes, it is possible, do we want this? Now we allow any image resolution and scale it to fit the apartment ad.

About the 414 response, could you provide the images of the apartment that cause this error?
The apartment id would be helpful too.

**Comment by alonttal** [comment]
I think we do. I've added an image gallery (carousel) that displays apartment's images in large. I want all the images to have a unified resolution that will more-or-less scale nicely within. also large images may hurt performence.

about the other error - I take my words back, it was something i've done wrong.

**Comment by alonttal** [comment]
Also,
need to extract the Azure-image logic from the route. I think it should be used as a service (under "services") that supplies API. The route should not know it is using Azure.

**Comment by idanyadgar** [comment]
I agree. Opened #436
