### ISSUE TITLE
[User's Manual] How to publish new apartment

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#429]
write a short manual on how to publish new apartment ad.
it needs to include all the preconditions (login/register), constraints (what can/cannot be done), how to do it, and so on.

**Comment by OrAbramovich** [comment]
@Danielohayon - what is the status?

**Comment by chananbental** [comment]
@OrAbramovich qould you like for me to do this?

**Comment by alonttal** [comment]
@chananbental 
Hi Chanan, yes talk with @Danielohayon and update us if you are doing it in the next 4 hours.
Thank you!

**Comment by OrAbramovich** [comment]
@Danielohayon did it.

**Comment by OrAbramovich** [comment]
Done.
