### ISSUE TITLE
Add forms errors

### ISSUE THREAD

**Issue by idanyadgar** [TechnionYearlyProject/Roommates#431]
### Registration form:
No error is shown when a user tries to register with an already exists email.

### Add comment:
No error is shown when a user tries to add an invalid comment.
No error is shown when an unauthorized user tries to add a comment.

### Add apartment form:
No error is shown in case of an invalid input by the user.

**Comment by alonttal** [comment]
Hi Idan,
An unauthorized user should not have an option to add a comment. Did you mean "unverified"?

**Comment by idanyadgar** [comment]
If I log in and stay in the main page enough time, the token expires and I become unauthorized, but I can still see the "add comment" option (it was there since I was logged in at first).
We should show the error, if there is any, when trying to comment (too short or any other error).

BTW, the option of "add comment" does not appear if the user is unverified, which is good, and its not the case I am talking about.

**Comment by idanyadgar** [comment]
Also, I believe that there is no need of limiting the comment with a minimum length. Comments with even 1 character should be okay (we can think of a case when a comment with the content "6" is okay).

**Comment by alonttal** [comment]
Alright , cool i didn't remember what I did there..
I think the back end is limiting comment's length. If you plan to change it in the front then it should also be changed in the back.

**Comment by idanyadgar** [comment]
Time estimation: 2h.
