### ISSUE TITLE
Create Image dialog for apartment ad

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#435]
edit: dialog (modal) will be opened when clicking on the image portion of an ad. It will contain a carousel of the images. 
estimated time: 3 hours

**Comment by alonttal** [comment]
@idanyadgar 
edited.

done. actual time: 2.5 hours

**Comment by alonttal** [comment]
done. actual time: 20 min.
I've also added a "start-date" attribute to calendar to set up the starting date of the calendar.

**Comment by idanyadgar** [comment]
@alonttal Fixed. Try it now.

**Comment by alonttal** [comment]
Nice, the problem is that it influces all the the components using the same classes since it's not "scoped". You can see, for example, that the images of the ads have shrinked.
