### ISSUE TITLE
Slider jumps five values down when changed. 

### ISSUE THREAD

**Issue by Danielohayon** [TechnionYearlyProject/Roommates#473]
In page "Add Apartment" When setting the slider's "Number of roommates I'm looking for*" to a certain value and then pressing it again to drag it to a different value it jumps 5 values down. Same with the "Total number of roommates" slider that jumps 6 values down

**Comment by alonttal** [comment]
estimated time: 15 min

**Comment by alonttal** [comment]
done.
time 15 min
