### ISSUE TITLE
Click to complete doesn't work in "Add Apartment" page

### ISSUE THREAD

**Issue by Danielohayon** [TechnionYearlyProject/Roommates#474]
In the "Add Apartment" page when for example writing in the "Address" field "fa" the auto complete suggest "Fabregat Street in Ramat Gan, Israel" but when clicking it with the mouse it does not complete it. 
*Note that when pressing the downwards arrow in the keyboard when the street is suggested and then clicking Enter it does work.

**Comment by alonttal** [comment]
hi,
this bug was fixed here: #464 
please pull
