### ISSUE TITLE
Allows setting apartment fields with illogical values. And no error feedback in the second try.

### ISSUE THREAD

**Issue by Danielohayon** [TechnionYearlyProject/Roommates#475]
When filling an apartment's details with illogical values such as: negative values of "Total Floors", "Street Number", "Apartment Number". And a value of zero for "Number of rooms" and "Size".
It doesn't mark them with a red underline so the user doesn't know they are wrong. Then when going to advertise the apartment it says "Unknown Error" so it is still unclear for the user which values were wrong. 
Then if the user goes back and changes some of the illogical values to logical ones but leaves some fields with illogical values and tries to advertise the apartment again he doesn't even get an error message and nothing happens, he just stays in the same page. No feedback is given so he can't know if the apartment was advertised or if the process failed or even why it failed.

*Note: The fields name "size" should start with an uppercase letter as do the rest of the field names.

**Comment by alonttal** [comment]
estimated time: 15 min

**Comment by alonttal** [comment]
fixed: capability of inputing invalid values

**Comment by alonttal** [comment]
fixed:
- error message not showing
- size -> Size
- the error messages should be fixed on back-end side. the server sends "unknown-error" so the front-end has no way to know which error happened.

**Comment by alonttal** [comment]
closed.
