### ISSUE TITLE
Email is case sensitive. 

### ISSUE THREAD

**Issue by Danielohayon** [TechnionYearlyProject/Roommates#477]
If you register with an email such as for example: "Danielohayon@gmail.com" and then try to login in with the mail "danielohayon@gamil.com" it wouldn't work.
An email should not be case sensitive.

**Comment by OrAbramovich** [comment]
Time estimation: 0.25 hour + adding tests (1 hour).

**Comment by OrAbramovich** [comment]
Actual time: 1.5 hours (including tests).
