### ISSUE TITLE
Publisher Profile in an apartment

### ISSUE THREAD

**Issue by Danielohayon** [TechnionYearlyProject/Roommates#478]
When viewing an apartment in the search section, if you click on the "Publisher profile" button the publisher's profile is not clickable. Meaning, you can't click the circle representing him and go to his profile to message him. 
In addition the "Enable notifications" toggle does not toggle on when you click it in the same view.

**Comment by alonttal** [comment]
estimated time: 15 min

**Comment by alonttal** [comment]
fixed. time 15 min.
now the publisher avatar is clickable.
The toggle is not a bug since it has no role atm.
