### ISSUE TITLE
Bug: Notifications are not displayed (sometimes)

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#497]
For some reason there is an issue that notifications are not displayed. I don't know whether it's a front-end or back-end issue. Has to reproduce + investigate.

**Comment by alonttal** [comment]
this is fixed.
total time: 1.5 hours

**Comment by alonttal** [comment]
@OrAbramovich 
not sure if this is relevant anymore, please update.

**Comment by OrAbramovich** [comment]
Probably caused by not calling the socket connection function. Page has to be refreshed on login & logout.

**Comment by alonttal** [comment]
done 
time: 2 hours.
