### ISSUE TITLE
Design private messaging layout in Front end

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#498]
Make a complete documented design of private messaging mechanism in the front-end.

**Comment by chananbental** [comment]
estimated 0.001 hours

**Comment by idanyadgar** [comment]
Decided to full-design it in PS, took 1 hour.

**Comment by idanyadgar** [comment]
![Private messaging design](https://user-images.githubusercontent.com/2212604/40967069-d0149f96-68ba-11e8-89f1-2537cc23846b.png)

**Comment by alonttal** [comment]
@idanyadgar
Wow! Great job!
2 comments:
1. How does it look on smaller screen? 
2. Maybe you should consider placing it in a "container fluid"?

**Comment by idanyadgar** [comment]
@alonttal 
1. We need to think about a solution for the contacts.
2. Took your suggestion. :)

You can see the results in private-messaging-feature branch.
