### ISSUE TITLE
Integrate apartment page with the backend

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#500]
apartment page is static atm

**Comment by omrihuller** [comment]
estimated: 3

**Comment by Danielohayon** [comment]
I only had i hour to work on it so I haven't made much progress, mainly spent the time understating how the flow of the page is built. 
Time spent: 1 hour.

**Comment by chananbental** [comment]
estimated: 3 hours

**Comment by OrAbramovich** [comment]
Approved with the weekly manager @chananbental that task #543  is prioritized over this one so it goes out of sprint.

**Comment by alonttal** [comment]
#543 - includes integration

closed
