### ISSUE TITLE
Group management page

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#507]
add label to the apartment card, with price and match score of the best group for this apartment 

add the groups to apartment page
there you can accept/deny/bid bid redirects to payment page

**Comment by omrihuller** [comment]
estimate: 8 hours

**Comment by alonttal** [comment]
follow up:
#515

**Comment by idanyadgar** [comment]
@alonttal Can we close this?

**Comment by alonttal** [comment]
Hi @idanyadgar
The page is still WIP. It'll be closed soon.

**Comment by alonttal** [comment]
This is closed.
The Close The Deal feature is 100% complete.
it is still lacking the ability to changed the status of a group to "closed" (or "payed" - if you want to call it that way).
