### ISSUE TITLE
Apartment owner groups page

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#509]
show all active groups and let owner choose

**Comment by chananbental** [comment]
estimated 4 hours

**Comment by alonttal** [comment]
Hi,
what does this issue mean?

**Comment by omrihuller** [comment]
@alonttal 
as I understand it, its to change the group page view in case the user is the owner.

so far I cant see the full group page, firstly the login bug was a problem 
but now the page is empty and im not sure how to add groups to the layout

**Comment by alonttal** [comment]
By "empty" you mean that there are no groups?

**Comment by omrihuller** [comment]
Thats exactly what I meant.

as for the first option what do you mean? is it a route?
as for robomongo I just downloaded it and will figure out how to use it.

**Comment by alonttal** [comment]
You can build any group you want through the option to build a group in the site. It's already working and a part of the groups page.

**Comment by omrihuller** [comment]
the bug was due to hard coded data that wasnt present on my PC
closed
