### ISSUE TITLE
Create The Poster Template

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#519]
It needs to be ready by 5th of June.

**Comment by alonttal** [comment]
1st version:

[Poster Template Yearly 2018.pptx](https://github.com/TechnionYearlyProject/Roommates/files/2066226/Poster.Template.Yearly.2018.pptx)

actual time: 4 hours

**Comment by OrAbramovich** [comment]
Hi @alonttal ,

In order to demonstrate the simplicity and the funnel, I think that we should add the flow of the site to the poster. Example is attached. What do you think?
[PosterFlow.pptx](https://github.com/TechnionYearlyProject/Roommates/files/2070949/PosterFlow.pptx)

**Comment by alonttal** [comment]
uploaded final version:

[Poster Template Yearly 2018.pptx](https://github.com/TechnionYearlyProject/Roommates/files/2071495/Poster.Template.Yearly.2018.pptx)

**Comment by alonttal** [comment]
closing.
The poster was added to wiki.
total time: 5 hours
