### ISSUE TITLE
Front end: create payment page layout

### ISSUE THREAD

**Issue by idanyadgar** [TechnionYearlyProject/Roommates#520]
Now we have a static payment page that contains a single paypal button.

The task:
Build the page itself, around the paypal button (payment details etc.), add links to the relevant payment page in the right places and handle the "payment complete" event (redirect to the next step of close-the-deal).

This issue follows #512.

**Comment by chananbental** [comment]
decide on layout

**Comment by omrihuller** [comment]
a layout consisting of 2 dialog contracts (terms of service & apartment contract) and the payment button.
agreeing to both contracts and paying finishes the process.
