### ISSUE TITLE
Azure: modify the payment-complete function to insert the transaction to the DB

### ISSUE THREAD

**Issue by idanyadgar** [TechnionYearlyProject/Roommates#523]
After a payment is made, the function is invoked, and right now it does nothing but logging the raw data received in the request.

Modify the function so that it receives a paypal event, and records the transaction in the DB if the payment was successfully made.

This issue follows: #512.

**Comment by chananbental** [comment]
estimated 3 hours
depends on #531

**Comment by OrAbramovich** [comment]
Not relevant anymore.
