### ISSUE TITLE
Back-End: change group schema members arrays

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#526]
currently: array for members and array for statuses
after: one array of member + status couples

**Comment by chananbental** [comment]
assigned
estimated 3 hours

**Comment by alonttal** [comment]
done.
group schema:
- members: Array of objects {id,status} - id is the user's id and status is his status (accepted, declined, pending,...)
- createdAt: group creation time.
- score: group score: calculated by members matching score
- status: the group's status (open, closed, dealClosed,...)
- _apartmentId: ref to apartment.
