### ISSUE TITLE
implement apartment suggestion

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#534]
acoording to design #335 
estimated 9 hours

**Comment by alonttal** [comment]
Hi Chanan,
how's it going with it?

**Comment by chananbental** [comment]
work progress for last week:
model and 2 new routes: POST /searchs  & GET /searchs/toNotify
the first saves a search the second find the users to be notified and returns them
tested them
whats left:
connecting the POST route to the front end #559
adding the second route to Azure as a timed piece of code #560

**Comment by chananbental** [comment]
i had to rewrite some of the code and added a test
this took an aditional 5 hours, if not more
