### ISSUE TITLE
update GET reviews/:long/:lat route

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#535]
update to get all reviews other then aggregated
estimated 1 hour

**Comment by alonttal** [comment]
Hi @chananbental ,
what does this issue mean?
I thought reviews feature was closed last weak.

**Comment by alonttal** [comment]
@chananbental 

please update. closed?

**Comment by chananbental** [comment]
to answer your previous question first, due to a misunderstanding of what the route does, a new route was made that only returned the reviews with out checking relevency and calculating the scores in the front end. this issue is to update the origional route to send all the reviews as well as the calculation and check relevency.
this was not done yet due to the need to implement the  new apartment notification first
i am hoping to get to this by next week, will update on progress

**Comment by chananbental** [comment]
we decided the current route is enough
worked for 0.5 hour
closed
