### ISSUE TITLE
Front-end: Rebuild apartment page

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#543]
There existing apartment page is totally broken. New one has to be build.
Approved with the weekly manager @chananbental that this task is prioritized over the #533 , #500  (so they go out of sprint).

**Comment by OrAbramovich** [comment]
Estimated time: 15 hours.

**Comment by OrAbramovich** [comment]
It has now the same template as the apartment details card displayed in the main page (collapsed). @alonttal  takes it this week.

**Comment by alonttal** [comment]
sub-tasks:
#545

**Comment by alonttal** [comment]
done.
Actual time: ~20 hours

**Comment by alonttal** [comment]
Merged ApartmentPage branch with master.
Pushed.

closed.
