### ISSUE TITLE
Find bugs for the end of semester client challenge

### ISSUE THREAD

**Issue by idanyadgar** [TechnionYearlyProject/Roommates#565]
Make sure that in the client challenge it will be hard for the others to find real bugs.
Open issues for each found bug.

This will reduce the amount of work we will have after the client challenge.
This includes re-cloning the repository to your local machine and installing all dependencies.

Estimated time: 9 hours.

**Comment by alonttal** [comment]
bug I found:
back-end is failing to update apartment's images (route patch /apartments/:id).
back-end: can't update apartment's address.

**Comment by omrihuller** [comment]
@alonttal  
hi alon i'll add them to the list. who wrote the routes that arent working?

at the moment I dont see an option to edit an apartment I posted in the front end is it a bug? or does it need to be implemented?

**Comment by alonttal** [comment]
Hi @omrihuller
It is already implemented. Maybe i should have made it more prominent. If you are the publisher, you should see the edit button above the price.

**Comment by omrihuller** [comment]
I see it now, dont know how I missed it

**Comment by omrihuller** [comment]
total time so far: 12 hours
