### ISSUE TITLE
Bug: fix email already in use problem

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#572]
email already in use appeared for every mail I have put.

*happened after registering and not confirming an email

**Comment by omrihuller** [comment]
error: /users returned: 400 for the following request: {"email":"unusedemail@gmail.com","password":"123456","firstName":"no","lastName":"no","birthdate":"1-1-1992","gender":"male"}

**Comment by alonttal** [comment]
Hi @omrihuller ,
I'm unable to reproduce the bug.
i tried - registering without verifying, then loging out, then registering using other email address,
and it worked fine.

**Comment by omrihuller** [comment]
Hi @alonttal,
I checked now after I pulled and it works fine, 
I hope one of the fixes affected this too, I'll close it for now and see if it happens again

closed for now.
