### ISSUE TITLE
Bug: Main details date, address

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#576]
if I fill the entrance date (or address)  field and delete, there is no longer an error message that this field is required and there is no error on the "main details" section.
it saves the data I delete and if I post it the data is there

need to show error in case the field is empty even if deleted.
Estimation 2 hours

**Comment by OrAbramovich** [comment]
1. Label attached to the calendar (which displays selected date) should be read only.
2. Should check length of address text field

**Comment by OrAbramovich** [comment]
Actual time: 0.3 hour.

**Comment by OrAbramovich** [comment]
Done.
