### ISSUE TITLE
Bug: Cant update apartment images

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#580]
when editing an apartment I own I cant **ADD** any photos (I can delete photos entered during creation)
when I upload a picture and press the update button an error message appears with "unknown error occurred"

seems to be a problem in the route  (patch /apartments/:id).

Estimation: 4 hours

**Comment by alonttal** [comment]
disabled feature for now. edit page does not offer updating images

**Comment by alonttal** [comment]
closed
