### ISSUE TITLE
Bug: Cant update apartment address

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#581]
street and number dont change after pressing update.

console shows:
Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at eval (webpack-internal:///./node_modules/vuetify/dist/vuetify.js:3499:50)

**Comment by idanyadgar** [comment]
FIxed. Disabled the option of editing address, it does not make sense.
