### ISSUE TITLE
Bug: email field overflow causes crash

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#588]
when I fill the email field in login/registration with a lot of input it causes the site to stop and then crash

this doesn't happen with other fields.

**Comment by omrihuller** [comment]
@alonttal
can you confirm that its not just happening to me?

**Comment by omrihuller** [comment]
for example: 
I put in email: 1234567890123456789012345678901234567890 (40 characters)
and try to put the password in and its stuck
after about a minute I get a "page non responsive" error

**Comment by alonttal** [comment]
@omrihuller 
Hi,
That was a nice catch! I fixed the problem.
Make sure to run "npm i" again after pulling.

**Comment by alonttal** [comment]
closed.
