### ISSUE TITLE
Apartment page: enable notifications 

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#593]
nothing happens when trying to toggle this button (at least in the front end)

if it exists in the back end we need to connect it.

**Comment by OrAbramovich** [comment]
Hi @omrihuller ,
It was a dummy slider (wan't connected to the back-end).
I have just connected it to the back-end and it should work. 
See commit 004ec87:
https://github.com/TechnionYearlyProject/Roommates/commit/004ec87562ae70649ada3c00e01417d2cc6efc16

**Comment by OrAbramovich** [comment]
@omrihuller ,
It would be great if you could update the Master and verify it. Once verified - you can close it.
BTW, the slider is available in the apartment page and was removed from the apartment ad in the main page.

**Comment by omrihuller** [comment]
Works as intended, notifications are enabled on apartments you post by default and you can change at any  time

closed
