### ISSUE TITLE
Continue writing user manual

### ISSUE THREAD

**Issue by Danielohayon** [TechnionYearlyProject/Roommates#603]
followup to issue #207 

Time estimation: 9 hours.

**Comment by OrAbramovich** [comment]
Hi @Danielohayon ,

What is the status of the task?

**Comment by Danielohayon** [comment]
Updated version: 
[Final User Manual.docx](https://github.com/TechnionYearlyProject/Roommates/files/2130825/Final.User.Manual.docx)

**Comment by Danielohayon** [comment]
Updated version:

[User Manual.docx](https://github.com/TechnionYearlyProject/Roommates/files/2130858/User.Manual.docx)

**Comment by Danielohayon** [comment]
Updated version:

[User Manual.docx](https://github.com/TechnionYearlyProject/Roommates/files/2130877/User.Manual.docx)

**Comment by chananbental** [comment]
shouldn't the user manual be in the wiki?

**Comment by chananbental** [comment]
[User.Manual.docx](https://github.com/TechnionYearlyProject/Roommates/files/2131152/User.Manual.docx)

added group creation and close the deal

**Comment by chananbental** [comment]
[User.Manual.docx](https://github.com/TechnionYearlyProject/Roommates/files/2131167/User.Manual.docx)

added the close the deal to the index with hyper-link

**Comment by Danielohayon** [comment]
Added reseting password and images to the manual: 

[Final User Manual.docx](https://github.com/TechnionYearlyProject/Roommates/files/2131210/Final.User.Manual.docx)

**Comment by alonttal** [comment]
Hi so are we done?

**Comment by chananbental** [comment]
[Final.User.Manual.docx](https://github.com/TechnionYearlyProject/Roommates/files/2131250/Final.User.Manual.docx)
please check my work, i belive it is corrrect this time

**Comment by chananbental** [comment]
sorry last fix:
[Final.User.Manual.docx](https://github.com/TechnionYearlyProject/Roommates/files/2131262/Final.User.Manual.docx)

**Comment by chananbental** [comment]
[Final.User.Manual.docx](https://github.com/TechnionYearlyProject/Roommates/files/2132231/Final.User.Manual.docx)

last edtion
