### ISSUE TITLE
continue to connect POST /searchs to front end

### ISSUE THREAD

**Issue by Danielohayon** [TechnionYearlyProject/Roommates#604]
find the search activation and add the search saving route call

estimated time: 2 hours
follows #559

**Comment by chananbental** [comment]
was able to connect only thing left is to call GET /searchs/toNotify, once a day to actualy send emails
the route exists.
for futer work, just comment back in a small chunck of code in AppDrawer.vue to save searchs
then add the call to the GET route #605

**Comment by chananbental** [comment]
actual time: 10 hours
