### ISSUE TITLE
continue to Find bugs for the end of semester client challenge

### ISSUE THREAD

**Issue by Danielohayon** [TechnionYearlyProject/Roommates#607]
followup to: #565
Make sure that in the client challenge it will be hard for the others to find real bugs.
Open issues for each found bug.

This will reduce the amount of work we will have after the client challenge.
This includes re-cloning the repository to your local machine and installing all dependencies.

Estimated time: 5 hours.

**Comment by omrihuller** [comment]
**test log:**

notifications: 
owner is notified on users expressing interest about his apartments
- user notified on his own likes. user X liked an apartment owned by user Y, right after that user X has a notification "new interest by user X". #609

**Comment by omrihuller** [comment]
actual time: 8 hours

**Comment by omrihuller** [comment]
total time: 7 hours
