### ISSUE TITLE
Bug: user notified on his own likes

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#609]
user X liked an apartment owned by user Y, right after that user X has a notification "new interest by user X". 
this might be connected to the fact that I logged to user Y and then to user X.

![capture](https://user-images.githubusercontent.com/12989643/41667682-41f234fa-74b6-11e8-846c-1dc079fa1513.PNG)

**Comment by alonttal** [comment]
This is extremely wierd behavior that i haven't tackled upon.
it certainly needs to be fixed.

**Comment by OrAbramovich** [comment]
Hi @omrihuller,  

Is it reproducible without changing users?

**Comment by OrAbramovich** [comment]
Probably same root cause as #497

**Comment by alonttal** [comment]
done 
time: 2 hours.
