### ISSUE TITLE
Bug: owner isn't notified when a new full group is available

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#610]
owner should get a notification when a full group has been formed in one of his apartments (there is a group where all the users accepted the group)

**Comment by alonttal** [comment]
My guess is that the front-end is not coded to hook these kind of notifications.
it need to be implemented.

**Comment by OrAbramovich** [comment]
Time estimation - after  #619 implementation - 0.5 hour (incl. manual test)

**Comment by OrAbramovich** [comment]
Actual time: 0.3 hour.

**Comment by OrAbramovich** [comment]
Done.
