### ISSUE TITLE
Bug: User not notified when he's in a group

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#614]
if a user added me to a group, im not notified 
 
similar to owner not getting notified on a full group #610 
these 2 are critical bugs since they are an integral part of the  CloseTheDeal flow

**Comment by alonttal** [comment]
My guess is that the front-end is not coded to hook these kind of notifications.
it need to be implemented.

**Comment by OrAbramovich** [comment]
I am on it

**Comment by OrAbramovich** [comment]
Estimated time: 0.75 hour.

**Comment by OrAbramovich** [comment]
Alon's guess is correct, will be fixed soon.

**Comment by OrAbramovich** [comment]
Actual time: 0.3 hour (incl. manual test)

**Comment by OrAbramovich** [comment]
Done.
