### ISSUE TITLE
Back-end: Front-end: Add new notification type "group accepted"

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#619]
So we will be able to notify apartment owner once a group is accepted by all members.

**Comment by OrAbramovich** [comment]
Estimated time: 0.5 hour.

**Comment by alonttal** [comment]
I've already add a notification type for groups.

**Comment by OrAbramovich** [comment]
Hi @alonttal ,
You added a notification for "NEW_GROUP_CREATION". Do you have other types that were not merged with the master?

**Comment by alonttal** [comment]
you are correct sir.
you can rename this notification and reuse or create a new one - which you feel is best.

**Comment by OrAbramovich** [comment]
Actual time: 0.3 hour.

**Comment by OrAbramovich** [comment]
Done.
