### ISSUE TITLE
Bug: Both search and add review modals can be opened in reviews page

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#629]
![image](https://user-images.githubusercontent.com/16474068/41796051-9fb97720-766d-11e8-8526-cd5731529db2.png)

on one another. need to close all windows before opening one..

**Comment by OrAbramovich** [comment]
Estimated time: 0.25 hour (incl. manual test)

**Comment by OrAbramovich** [comment]
Actual time: 0.25 hour (incl. manual test)

**Comment by OrAbramovich** [comment]
Done.
