### ISSUE TITLE
[User Manual] write how to use area review

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#637]
write user manual for user that includes:
 - how to submit a review.
 - how to see an area's review

estimated time: 1.5 hours

**Comment by chananbental** [comment]
@Danielohayon you told me your finished, right?

**Comment by chananbental** [comment]
@Danielohayon dont forget to upload the manual and add to wiki links under "User Manual"

**Comment by OrAbramovich** [comment]
@Danielohayon did it.
